version: "1.0"



services:
  api01: &api
    image: api_c:tag
    hostname: api01
    environment:
       PROCESSOS: "25"
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
      - "3007:3007"
      - "3008:3008"
      - "3009:3009"
      - "3010:3010"
      - "3011:3011"
      - "3012:3012"
      - "3013:3013"
      - "3014:3014"
      - "3015:3015"
      - "3016:3016"
      - "3017:3017"
      - "3018:3018"
      - "3019:3019"
      - "3020:3020"

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "400MB"



  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1