version: "1.0"



services:
  apiend: &api
    image: rinha_de_back_end_oui:0.2
    hostname: apiend
    environment:
      #isso totaliza 80 processos simultaneos, já que ambas as rotas
      ## vão forkear até 35 processos
       PROCESSOS: "20"
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"

    volumes:
      - ./start.sh:/start.sh

    deploy:
      resources:
        limits:
          cpus: "1.2"
          memory: "350MB"



  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apiend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1