version: "1.0"

services:
  api01: &api
    image: api_c:tag
    hostname: api01
    environment:
       PORTA: "8081"
       PROCESSOS: "4"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:

        PORTA: "8082"
        PROCESSOS: "4"
    ports:
      - "8082:8082"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1