version: "1.0"



services:
  api01: &api
    image: api_c:tag
    hostname: api01
    environment:
       PROCESSOS: "4"
    ports:
      - "3000:3002"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "400MB"



  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1