version: "1.0"



services:
  api01: &api
    image: api_c:tag
    hostname: api01
    environment:
       PROCESSOS: "10"
    ports:
      - "3001:3001"
      - "3002:3002"
      
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "400MB"



  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1