version: "1.0"

services:
  api01: &api
    image: api_c:tag
    hostname: api01
    environment:
      - PORTA=3001
      - PROCESSOS=4
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - PORTA=3002
    ports:
      - "3002:3000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1