version: "1.0"



services:
  apiend: &api
    image: api_c:tag
    hostname: apiend
    environment:
       PROCESSOS: "35"
    ports:
      - "3001:3001"
      - "3002:3002"
      
    deploy:
      resources:
        limits:
          cpus: "1.1"
          memory: "300MB"



  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apiend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "100MB"



networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1