#define PORTA_PADRAO 9999
#define INCONSISTENCIA 422
#define NAO_ENCONTRADO 404
#define MAXIMO_BODY 200
#define RETORNO_OK 200
#define MAXIMO_TRANSACOES 10

#define ESPERA_PELA_LUZ_MS 5
#define MAXIMO_FILA 100000
#define MAXIMO_REQUEST 2
#define TIMEOUT_FUNCAO 3
#define TIMEOUT_CLIENTE 3