#include "rota_parser/rota_parser.c"
#include "extra/extra.c"
#include "criacao_de_clientes/criacao_de_clientes.c"
#include "transacoes/parseamento.c"
#include "transacoes/transacoes.c"
#include "transacoes/escrita.c"
#include "extrato/extrato.c"
#include "observabilidade/observabilidade.c"
